## 워드클라우드 자체실습 1 : 이달의 소녀(LOONA) - Number 1 ####
## ---------------------------------------------------------------------- ##
# step 0 : KoNLP 패키지 로드 중 오류 처방 사이트
#Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-14.0.1")
#Sys.getenv("JAVA_HOME")
#install.packages("rJava")
#library(rJava)

# step 1
#install.packages("KoNLP")
#install.packages("wordcloud2")
#library(KoNLP)
#library(wordcloud2)

# step 2
#useSejongDic()
#useNIADic()
#useSystemDic()

## ---------------------------------------------------------------------- ##
# step 1~2 : 패키지 설치 및 한글사전 설정
## R KoNLP & wordcloud2 설치 및 확인
install.packages("multilinguer")
library(multilinguer)

install.packages("wordcloud2")
library(wordcloud2)

install_jdk()
install.packages(c("stringr", "hash", "tau", "Sejong", "RSQLite", "devtools"), type = "binary")
install.packages("remotes")
remotes::install_github("haven-jeon/KoNLP",  upgrade = "never",  INSTALL_opts=c("--no-multiarch"))

library(KoNLP)
# 세종 사전 사용 지정
useSejongDic( ) 
## ---------------------------------------------------------------------- ##

setwd("F:/")
# step 3 : 텍스트데이터 가져오기 및 명사 추출
word_data <- readLines("LOONA_Number1.txt", encoding = "UTF-8")
word_data

word_data2 <- sapply(word_data, extractNoun, USE.NAMES = F)
word_data2

# step 4 : 리스트 자료구조를 벡터로 변환
undata <- unlist(word_data2)
undata

# step 5 : 사용빈도 계산
word_table <- table(undata)
word_table

sort(word_table, decreasing = T)

# step 6 : 특정 단어 제외 or 삭제
# 추임새 "Du"와 "Ru" 제거
undata <- gsub("Du", "", undata)
undata <- gsub("Ru", "", undata)
# "Number"를 "Number1"으로 바꿔서 중복 제거
undata <- gsub("Number", "Number1", undata)
# "yea" 제거
undata <- gsub("yea", "", undata)
undata

# step 7 : 사용빈도 재 계산
word_table <- table(undata)
word_table

sort(word_table, decreasing = T)

# step 8 : 필터링 : 두 글자 이상만 필터
undata2 <- Filter(function(x) { nchar(x) >= 2 }, undata)
undata2

word_table2 <- table(undata2)
word_table2

# step 9 : 데이터 정렬
word_table2 <- sort(word_table2, decreasing = T)
word_table2

# step 10 : 워드클라우드 생성
wordcloud2(word_table2)

# step 11 : 배경/색상 변경 
wordcloud2(word_table2, color = "random-light", 
           backgroundColor = "black")

# step 12 : 배경/색상/모양 변경 
wordcloud2(word_table2, size = 0.8, shape = 'star', 
           color = "random-light", backgroundColor = "Pink")

?wordcloud2()

wordcloud2(word_table2, 
           rotateRatio = 0.5,
           minRotation = -pi/6, 
           maxRotation = -pi/6,
           backgroundColor = "white") 


# gsub("[A-Za-z0-9]", "", artsong) : 영어와 숫자 제거
# gsub("[~!@#$%^&*()]", "", artsong) : 특수문자 제거
# gsub("[ㄱ-ㅎ]", "", artsong) : ㄱ부터 ㅎ까지 자음 제거
# gsub("[ㅜ|ㅠ]+", "", artsong) : 한 개 이상의 ㅜ와 ㅠ 제거

## 워드클라우드 자체실습 2 : 이달의 소녀(LOONA) 전곡 (2016. 10 ViViD ~ 2020. 4 시한바돌) ####
# [HeeJin] ViViD & ViViD (Acoustic Mix) / [HyunJin] I’ll Be There & 다녀가요 (Around You)
# [HaSeul] The Carol & 소년, 소녀 (Let Me In) / [YeoJin] 키스는 다음에 (Kiss Later) & My Sunday & My Melody
# [1/3 Love&Live] 지금, 좋아해 (Love & Live) & You and Me Together & Fairy Tale & 3월을 기다려 (Valentine Girl)
# [ViVi] Everyday I Love You & Everyday I Need You / [1/3 Love&Evil] 알 수 없는 비밀 (Sonatine) & 비의 목소리 51db (Rain 51db)
# [Kim Lip] Eclipse & Twilight / [JinSoul] Singing in the Rain & Love Letter / [Choerry] Love Cherry Motion & Puzzle
# [OEC Mix&Match] Girl Front & LOONATIC & Chaotic & Starlight / [OEC Max&Match] Sweet Crazy Love & Uncover & ODD Front
# [Yves] new & D-1 / [The Carol 2.0] The Carol 2.0 / [Chuu] Heart Attack & Girl’s Talk / [Go Won] One & Only & See Saw 
# [Olivia Hye] Egoist & Rosy / [yyxy beatuy&thebeat] love4eva & frozen & one way & rendezvous 18.6y
# [+ +] Hi High & favOriTe & 열기 & Perfect Love & Stylish
# [X X] Butterfly & 위성(Satellite) & Curiosity & 색깔(Colors) & Where you at
# [#] So What & Number 1 & Oh (Yes I Am) & 땡땡땡 & 365 / [어서와 OST Part.8] 시간은 한 바퀴 돌아
# 중복곡, Intro, Inst 제외한 타이틀곡과 수록곡 59개 노래 분석


## ---------------------------------------------------------------------- ##
# Java 설정
#Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-14.0.1")
#Sys.getenv("JAVA_HOME")
#install.packages("rJava")
#library(rJava)

# 한글처리 패키지 KoNLP, 워드클라우드 패키지 wordcloud2 설치
#install.packages("KoNLP")
#install.packages("wordcloud2")
#library(KoNLP)
#library(wordcloud2)

# 한글사전 설정 (세종사전, NIA사전, 시스템사전)
#useSejongDic()
#useNIADic()
#useSystemDic()
## ---------------------------------------------------------------------- ##

## 패키지 설치 및 한글사전 설정
## R KoNLP & wordcloud2 설치 및 확인
install.packages("multilinguer")
library(multilinguer)

install.packages("wordcloud2")
library(wordcloud2)

install_jdk()
install.packages(c("stringr", "hash", "tau", "Sejong", "RSQLite", "devtools"), type = "binary")
install.packages("remotes")
remotes::install_github("haven-jeon/KoNLP",  upgrade = "never",  INSTALL_opts=c("--no-multiarch"))

library(KoNLP)
# 세종 사전 사용 지정
useSejongDic( ) 
## ---------------------------------------------------------------------- ##

# loonatheworld.text 파일 읽어오기, UTF-8로 인코딩
loona_lyrics <- readLines("loonatheworld.txt", encoding = "UTF-8")
head(loona_lyrics)
str(loona_lyrics)   # 구조 확인 : 문자형 벡터(문장) 3,315개

# 문장을 형태소로 변환하여 리스트 생성
loona_lyrics2 <- sapply(loona_lyrics, extractNoun, USE.NAMES = F)
head(loona_lyrics2)
is.list(loona_lyrics2)    # loona_lyrics2 변수가 리스트인가? = TRUE

# unlist() 함수 사용하여 형태소를 문자형 벡터로 전환
unlist_lyrics <- unlist(loona_lyrics2)
unlist_lyrics
is.vector(unlist_lyrics)  # unlist_lyrics 변수가 벡터인가 = TRUE
str(unlist_lyrics)        # 형태소 벡터의 구조 확인

# 형태소 벡터를 테이블로 변환 : 형태소의 사용빈도 확인
lyrics_table <- table(unlist_lyrics)
lyrics_table
lyrics_table <- sort(lyrics_table, decreasing = T) # 내림차순(decreasing=T) 정렬
str(lyrics_table)         # 형태소 테이블의 구조 확인

# + 문자형 벡터에서 gsub() 함수를 이용하여 잘못된 단어 찾아 바꾸기 ####
#   중요 : gsub() 함수는 해당 문자를 포함한 모든 문자열을 바꿈
# 끝 단어 한 자씩 빼먹은 경우 : 스펠링 채우기
# 한 글자 단어인 경우, 필터링을 위해 두 글자 이상으로 확대
# 대소문자 혼용을 소문자로 통일
unlist_lyrics <- gsub("heartre", "heart", unlist_lyrics)
unlist_lyrics <- gsub("I'", "I'll", unlist_lyrics)
unlist_lyrics <- gsub("highh", "high", unlist_lyrics)
unlist_lyrics <- gsub("lov", "love", unlist_lyrics)
unlist_lyrics <- gsub("ther", "there", unlist_lyrics)
unlist_lyrics <- gsub("Brfly", "Butterfly", unlist_lyrics)
unlist_lyrics <- gsub("Sinng", "Sing", unlist_lyrics)
unlist_lyrics <- gsub("Gi", "Girl", unlist_lyrics)
unlist_lyrics <- gsub("Eips", "Eclipse", unlist_lyrics)
unlist_lyrics <- gsub("Sund", "Sunday", unlist_lyrics)
unlist_lyrics <- gsub("Wing", "Wings", unlist_lyrics)
unlist_lyrics <- gsub("WingWings", "Wings", unlist_lyrics)
unlist_lyrics <- gsub("arend", "are", unlist_lyrics)
unlist_lyrics <- gsub("betr", "better", unlist_lyrics)
unlist_lyrics <- gsub("ba", "baby", unlist_lyrics)
unlist_lyrics <- gsub("bab", "baby", unlist_lyrics)
unlist_lyrics <- gsub("yea", "yeah", unlist_lyrics)
unlist_lyrics <- gsub("kno", "know", unlist_lyrics)
unlist_lyrics <- gsub("rai", "rain", unlist_lyrics)
unlist_lyrics <- gsub("Butterfl", "Butterfly", unlist_lyrics)
unlist_lyrics <- gsub("Eclips", "Eclipse", unlist_lyrics)
unlist_lyrics <- gsub("tim", "time", unlist_lyrics)
unlist_lyrics <- gsub("love4ev", "love4eva", unlist_lyrics)
unlist_lyrics <- gsub("onl", "only", unlist_lyrics)
unlist_lyrics <- gsub("toda", "today", unlist_lyrics)
unlist_lyrics <- gsub("beb", "bebe", unlist_lyrics)
unlist_lyrics <- gsub("ste", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("Motio", "Motion", unlist_lyrics)
unlist_lyrics <- gsub("Rainbo", "Rainbow", unlist_lyrics)
unlist_lyrics <- gsub("Dejav", "Dejavu", unlist_lyrics)
unlist_lyrics <- gsub("goodnes", "goodness", unlist_lyrics)
unlist_lyrics <- gsub("Flas", "Flash", unlist_lyrics)
unlist_lyrics <- gsub("hig", "high", unlist_lyrics)
unlist_lyrics <- gsub("highligh", "highlight", unlist_lyrics)
unlist_lyrics <- gsub("oka", "okay", unlist_lyrics)
unlist_lyrics <- gsub("slee", "sleep", unlist_lyrics)
unlist_lyrics <- gsub("Alrigh", "Alright", unlist_lyrics)
unlist_lyrics <- gsub("Curiosit", "Curiosity", unlist_lyrics)
unlist_lyrics <- gsub("Fantas", "Fantasy", unlist_lyrics)
unlist_lyrics <- gsub("favOriT", "favOriTe", unlist_lyrics)
unlist_lyrics <- gsub("fee", "feel", unlist_lyrics)
unlist_lyrics <- gsub("Impuls", "Impulse", unlist_lyrics)
unlist_lyrics <- gsub("insan", "insane", unlist_lyrics)
unlist_lyrics <- gsub("lette", "letter", unlist_lyrics)
unlist_lyrics <- gsub("Magi", "Magic", unlist_lyrics)
unlist_lyrics <- gsub("melod", "melody", unlist_lyrics)
unlist_lyrics <- gsub("mor", "more", unlist_lyrics)
unlist_lyrics <- gsub("nee", "need", unlist_lyrics)
unlist_lyrics <- gsub("nigh", "night", unlist_lyrics)
unlist_lyrics <- gsub("Nigh", "night", unlist_lyrics)
unlist_lyrics <- gsub("Psychoti", "Psychotic", unlist_lyrics)
unlist_lyrics <- gsub("Satellit", "Satellite", unlist_lyrics)
unlist_lyrics <- gsub("sta", "stay", unlist_lyrics)
unlist_lyrics <- gsub("stor", "story", unlist_lyrics)
unlist_lyrics <- gsub("sunda", "sunday", unlist_lyrics)
unlist_lyrics <- gsub("tha", "that", unlist_lyrics)
unlist_lyrics <- gsub("Tim", "Time", unlist_lyrics)
unlist_lyrics <- gsub("Tonigh", "Tonight", unlist_lyrics)
unlist_lyrics <- gsub("Troubl", "Trouble", unlist_lyrics)
unlist_lyrics <- gsub("Coo", "cool", unlist_lyrics)
unlist_lyrics <- gsub("yo", "you", unlist_lyrics)
unlist_lyrics <- gsub("Episod", "Episode", unlist_lyrics)
unlist_lyrics <- gsub("Errda", "Errday", unlist_lyrics)
unlist_lyrics <- gsub("fro", "from", unlist_lyrics)
unlist_lyrics <- gsub("flo", "flow", unlist_lyrics)
unlist_lyrics <- gsub("Flo", "flow", unlist_lyrics)
unlist_lyrics <- gsub("directio", "direction", unlist_lyrics)
unlist_lyrics <- gsub("blu", "blue", unlist_lyrics)
unlist_lyrics <- gsub("Cal", "Call", unlist_lyrics)
unlist_lyrics <- gsub("dow", "down", unlist_lyrics)
unlist_lyrics <- gsub("everyda", "everyday", unlist_lyrics)
unlist_lyrics <- gsub("craz", "crazy", unlist_lyrics)
unlist_lyrics <- gsub("Fee", "Feel", unlist_lyrics)
unlist_lyrics <- gsub("Goo", "Good", unlist_lyrics)
unlist_lyrics <- gsub("Ligh", "Light", unlist_lyrics)
unlist_lyrics <- gsub("loveed", "loved", unlist_lyrics)
unlist_lyrics <- gsub("Mirro", "Mirror", unlist_lyrics)
unlist_lyrics <- gsub("rld", "world", unlist_lyrics)
unlist_lyrics <- gsub("ros", "rosy", unlist_lyrics)
unlist_lyrics <- gsub("lif", "life", unlist_lyrics)
unlist_lyrics <- gsub("runwa", "runway", unlist_lyrics)
unlist_lyrics <- gsub("Spotligh", "Spotlight", unlist_lyrics)
unlist_lyrics <- gsub("Wha", "What", unlist_lyrics)
unlist_lyrics <- gsub("Bab", "baby", unlist_lyrics)
unlist_lyrics <- gsub("Yea", "yeah", unlist_lyrics)
unlist_lyrics <- gsub("righ", "right", unlist_lyrics)
unlist_lyrics <- gsub("righ", "right", unlist_lyrics)
unlist_lyrics <- gsub("Lov", "love", unlist_lyrics)
unlist_lyrics <- gsub("styl", "style", unlist_lyrics)
unlist_lyrics <- gsub("chaoti", "Chaotic", unlist_lyrics)
unlist_lyrics <- gsub("Goin", "Going", unlist_lyrics)
unlist_lyrics <- gsub("Melod", "Melody", unlist_lyrics)
unlist_lyrics <- gsub("togethe", "together", unlist_lyrics)
unlist_lyrics <- gsub("destin", "destiny", unlist_lyrics)
unlist_lyrics <- gsub("Destin", "destiny", unlist_lyrics)
unlist_lyrics <- gsub("Hig", "high", unlist_lyrics)
unlist_lyrics <- gsub("tru", "true", unlist_lyrics)
unlist_lyrics <- gsub("Darlin", "darling", unlist_lyrics)
unlist_lyrics <- gsub("lonel", "lonely", unlist_lyrics)
unlist_lyrics <- gsub("Ful", "full", unlist_lyrics)
unlist_lyrics <- gsub("Puzzl", "Puzzle", unlist_lyrics)
unlist_lyrics <- gsub("Win", "Wings", unlist_lyrics)
unlist_lyrics <- gsub("Bur", "Burn", unlist_lyrics)
unlist_lyrics <- gsub("da", "day", unlist_lyrics)
unlist_lyrics <- gsub("ar", "are", unlist_lyrics)
unlist_lyrics <- gsub("Are", "are", unlist_lyrics)
unlist_lyrics <- gsub("Blu", "Blue", unlist_lyrics)
unlist_lyrics <- gsub("contro", "control", unlist_lyrics)
unlist_lyrics <- gsub("everythin", "everything", unlist_lyrics)
unlist_lyrics <- gsub("Hus", "hush", unlist_lyrics)
unlist_lyrics <- gsub("Imagin", "imagine", unlist_lyrics)
unlist_lyrics <- gsub("ligh", "light", unlist_lyrics)
unlist_lyrics <- gsub("Light", "light", unlist_lyrics)
unlist_lyrics <- gsub("lis", "list", unlist_lyrics)
unlist_lyrics <- gsub("Mov", "Move", unlist_lyrics)
unlist_lyrics <- gsub("sam", "same", unlist_lyrics)
unlist_lyrics <- gsub("Secret", "secret", unlist_lyrics)
unlist_lyrics <- gsub("Someda", "someday", unlist_lyrics)
unlist_lyrics <- gsub("spac", "space", unlist_lyrics)
unlist_lyrics <- gsub("stayrte", "stay", unlist_lyrics)
unlist_lyrics <- gsub("Sunda", "Sunday", unlist_lyrics)
unlist_lyrics <- gsub("Toda", "Today", unlist_lyrics)
unlist_lyrics <- gsub("Univers", "universe", unlist_lyrics)
unlist_lyrics <- gsub("youre", "you're", unlist_lyrics)
unlist_lyrics <- gsub("agai", "again", unlist_lyrics)
unlist_lyrics <- gsub("attentio", "attention", unlist_lyrics)
unlist_lyrics <- gsub("aroun", "around", unlist_lyrics)
unlist_lyrics <- gsub("Ar", "art", unlist_lyrics)
unlist_lyrics <- gsub("bea", "beat", unlist_lyrics)
unlist_lyrics <- gsub("bes", "best", unlist_lyrics)
unlist_lyrics <- gsub("bette", "better", unlist_lyrics)
unlist_lyrics <- gsub("bla", "blah", unlist_lyrics)
unlist_lyrics <- gsub("Bling", "bling", unlist_lyrics)
unlist_lyrics <- gsub("bloomin", "blooming", unlist_lyrics)
unlist_lyrics <- gsub("Blue", "blue", unlist_lyrics)
unlist_lyrics <- gsub("Bo", "Boy", unlist_lyrics)
unlist_lyrics <- gsub("brightnes", "brightness", unlist_lyrics)
unlist_lyrics <- gsub("Bubbl", "Bubble", unlist_lyrics)
unlist_lyrics <- gsub("Butterflyies", "Butterfly", unlist_lyrics)
unlist_lyrics <- gsub("cha", "chat", unlist_lyrics)
unlist_lyrics <- gsub("Can't", "can't", unlist_lyrics)
unlist_lyrics <- gsub("Chocolat", "Chocolate", unlist_lyrics)
unlist_lyrics <- gsub("colo", "color", unlist_lyrics)
unlist_lyrics <- gsub("drea", "dream", unlist_lyrics)
unlist_lyrics <- gsub("emotio", "emotion", unlist_lyrics)
unlist_lyrics <- gsub("endin", "ending", unlist_lyrics)
unlist_lyrics <- gsub("everyoun", "everyone", unlist_lyrics)
unlist_lyrics <- gsub("fac", "face", unlist_lyrics)
unlist_lyrics <- gsub("Falling", "falling", unlist_lyrics)
unlist_lyrics <- gsub("fl", "fly", unlist_lyrics)
unlist_lyrics <- gsub("Fl", "fly", unlist_lyrics)
unlist_lyrics <- gsub("fo", "for", unlist_lyrics)
unlist_lyrics <- gsub("Gir", "girl", unlist_lyrics)
unlist_lyrics <- gsub("Insid", "inside", unlist_lyrics)
unlist_lyrics <- gsub("kis", "kiss", unlist_lyrics)
unlist_lyrics <- gsub("Kno", "Know", unlist_lyrics)
unlist_lyrics <- gsub("Lemonad", "Lemonade", unlist_lyrics)
unlist_lyrics <- gsub("les", "less", unlist_lyrics)
unlist_lyrics <- gsub("Mayb", "maybe", unlist_lyrics)
unlist_lyrics <- gsub("Memore", "Memory", unlist_lyrics)
unlist_lyrics <- gsub("Memorey", "Memory", unlist_lyrics)
unlist_lyrics <- gsub("Mileag", "Mileage", unlist_lyrics)
unlist_lyrics <- gsub("Mileg", "Mileage", unlist_lyrics)
unlist_lyrics <- gsub("miracl", "miracle", unlist_lyrics)
unlist_lyrics <- gsub("MiYesterdayr", "yesterday", unlist_lyrics)
unlist_lyrics <- gsub("MyYesterdayr", "yesterday", unlist_lyrics)
unlist_lyrics <- gsub("Moo", "mood", unlist_lyrics)
unlist_lyrics <- gsub("Moonlyigh", "moonlight", unlist_lyrics)
unlist_lyrics <- gsub("morenin", "morning", unlist_lyrics)
unlist_lyrics <- gsub("morening", "morning", unlist_lyrics)
unlist_lyrics <- gsub("Oka", "okay", unlist_lyrics)
unlist_lyrics <- gsub("onc", "once", unlist_lyrics)
unlist_lyrics <- gsub("Ou", "out", unlist_lyrics)
unlist_lyrics <- gsub("Over", "over", unlist_lyrics)
unlist_lyrics <- gsub("pla", "play", unlist_lyrics)
unlist_lyrics <- gsub("Questio", "Question", unlist_lyrics)
unlist_lyrics <- gsub("rendezvou", "rendezvous", unlist_lyrics)
unlist_lyrics <- gsub("Rendezvou", "rendezvous", unlist_lyrics)
unlist_lyrics <- gsub("SA", "saw", unlist_lyrics)
unlist_lyrics <- gsub("Shak", "Shake", unlist_lyrics)
unlist_lyrics <- gsub("shou", "shout", unlist_lyrics)
unlist_lyrics <- gsub("slowl", "slowly", unlist_lyrics)
unlist_lyrics <- gsub("Slowl", "slowly", unlist_lyrics)
unlist_lyrics <- gsub("softl", "softly", unlist_lyrics)
unlist_lyrics <- gsub("somewher", "somewhere", unlist_lyrics)
unlist_lyrics <- gsub("Son", "Song", unlist_lyrics)
unlist_lyrics <- gsub("soun", "sound", unlist_lyrics)
unlist_lyrics <- gsub("Starligh", "starlight", unlist_lyrics)
unlist_lyrics <- gsub("stayrligh", "starlight", unlist_lyrics)
unlist_lyrics <- gsub("sto", "stop", unlist_lyrics)
unlist_lyrics <- gsub("stylis", "stylish", unlist_lyrics)
unlist_lyrics <- gsub("Sunligh", "sunlight", unlist_lyrics)
unlist_lyrics <- gsub("Superstitio", "superstition", unlist_lyrics)
unlist_lyrics <- gsub("Welcom", "Welcome", unlist_lyrics)
unlist_lyrics <- gsub("worl", "world", unlist_lyrics)
unlist_lyrics <- gsub("맘", "마음", unlist_lyrics)
unlist_lyrics <- gsub("밤", "밤새", unlist_lyrics)
unlist_lyrics <- gsub("You", "you", unlist_lyrics)
unlist_lyrics <- gsub("High", "high", unlist_lyrics)
unlist_lyrics <- gsub("favOriTe", "favorite", unlist_lyrics)
unlist_lyrics <- gsub("사랑했으", "사랑했으면", unlist_lyrics)
unlist_lyrics <- gsub("갇혀버", "갇혀버린", unlist_lyrics)
unlist_lyrics <- gsub("따스", "따스했던", unlist_lyrics)
unlist_lyrics <- gsub("빨주", "빨주노초", unlist_lyrics)
unlist_lyrics <- gsub("있도", "있도록", unlist_lyrics)
unlist_lyrics <- gsub("모르", "모르게", unlist_lyrics)
unlist_lyrics <- gsub("하잖", "하잖아", unlist_lyrics)
unlist_lyrics <- gsub("밤새새", "밤새", unlist_lyrics)
unlist_lyrics <- gsub("빠져들겠", "빠져들겠지", unlist_lyrics)
unlist_lyrics <- gsub("빠져들", "빠져들어", unlist_lyrics)
unlist_lyrics <- gsub("스토", "스토리", unlist_lyrics)
unlist_lyrics <- gsub("진하", "진하게", unlist_lyrics)
unlist_lyrics <- gsub("힘드", "힘드니", unlist_lyrics)
unlist_lyrics <- gsub("것처", "것처럼", unlist_lyrics)
unlist_lyrics <- gsub("꿈같", "꿈같아", unlist_lyrics)
unlist_lyrics <- gsub("꿈꾸", "꿈꾸던", unlist_lyrics)
unlist_lyrics <- gsub("youu", "you", unlist_lyrics)
unlist_lyrics <- gsub("yeahh", "yeah", unlist_lyrics)
unlist_lyrics <- gsub("knoww", "know", unlist_lyrics)
unlist_lyrics <- gsub("lovee", "love", unlist_lyrics)
unlist_lyrics <- gsub("onlyy", "only", unlist_lyrics)
unlist_lyrics <- gsub("needd", "need", unlist_lyrics)
unlist_lyrics <- gsub("bebee", "bebe", unlist_lyrics)
unlist_lyrics <- gsub("babyy", "baby", unlist_lyrics)
unlist_lyrics <- gsub("lifee", "life", unlist_lyrics)
unlist_lyrics <- gsub("theree", "there", unlist_lyrics)
unlist_lyrics <- gsub("nightt", "night", unlist_lyrics)
unlist_lyrics <- gsub("downn", "down", unlist_lyrics)
unlist_lyrics <- gsub("feell", "feel", unlist_lyrics)
unlist_lyrics <- gsub("Feell", "feel", unlist_lyrics)
unlist_lyrics <- gsub("feellin", "feeling", unlist_lyrics)
unlist_lyrics <- gsub("Feellin", "feeling", unlist_lyrics)
unlist_lyrics <- gsub("Lightts", "light", unlist_lyrics)
unlist_lyrics <- gsub("rainns", "rains", unlist_lyrics)
unlist_lyrics <- gsub("timeeline", "timeline", unlist_lyrics)
unlist_lyrics <- gsub("Psycoticc", "Psychotic", unlist_lyrics)
unlist_lyrics <- gsub("stayy", "stay", unlist_lyrics)
unlist_lyrics <- gsub("Troublee", "Trouble", unlist_lyrics)
unlist_lyrics <- gsub("LiYesterdayn", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("Yesterdayp", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("YeYesterdayrda", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("highhligh", "highlight", unlist_lyrics)
unlist_lyrics <- gsub("Butterflyy", "Butterfly", unlist_lyrics)
unlist_lyrics <- gsub("See", "see", unlist_lyrics)
unlist_lyrics <- gsub("Goodd", "Good", unlist_lyrics)
unlist_lyrics <- gsub("Mirrorr", "Mirror", unlist_lyrics)
unlist_lyrics <- gsub("Timee", "time", unlist_lyrics)
unlist_lyrics <- gsub("timee", "time", unlist_lyrics)
unlist_lyrics <- gsub("Fantasyy", "fantasy", unlist_lyrics)
unlist_lyrics <- gsub("storym", "story", unlist_lyrics)
unlist_lyrics <- gsub("hea", "heart", unlist_lyrics)
unlist_lyrics <- gsub("chatnge", "change", unlist_lyrics)
unlist_lyrics <- gsub("flyy", "fly", unlist_lyrics)
unlist_lyrics <- gsub("rightt", "right", unlist_lyrics)
unlist_lyrics <- gsub("gir", "girl", unlist_lyrics)
unlist_lyrics <- gsub("bterfly", "Butterfly", unlist_lyrics)
unlist_lyrics <- gsub("Sundayyy", "Sunday", unlist_lyrics)
unlist_lyrics <- gsub("Boyy", "Boy", unlist_lyrics)
unlist_lyrics <- gsub("todayy", "today", unlist_lyrics)
unlist_lyrics <- gsub("Wingsg", "Wing", unlist_lyrics)
unlist_lyrics <- gsub("Wingsgs", "Wing", unlist_lyrics)
unlist_lyrics <- gsub("endingg", "ending", unlist_lyrics)
unlist_lyrics <- gsub("Eipse", "Eclipse", unlist_lyrics)
unlist_lyrics <- gsub("Whe", "Where", unlist_lyrics)
unlist_lyrics <- gsub("love4ev", "love4eva", unlist_lyrics)
unlist_lyrics <- gsub("I'", "I'll", unlist_lyrics)
unlist_lyrics <- gsub("am", "I'm", unlist_lyrics)
unlist_lyrics <- gsub("Che", "Cherry", unlist_lyrics)
unlist_lyrics <- gsub("betterr", "better", unlist_lyrics)
unlist_lyrics <- gsub("Yesterdayy", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("LiYesterdayyn", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("Yesterdayyp", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("rightt", "right", unlist_lyrics)
unlist_lyrics <- gsub("목소", "목소리", unlist_lyrics)
unlist_lyrics <- gsub("12", "12월", unlist_lyrics)
unlist_lyrics <- gsub("dayy", "day", unlist_lyrics)
unlist_lyrics <- gsub("feelin", "feeling", unlist_lyrics)
unlist_lyrics <- gsub("hushh", "hush", unlist_lyrics)
unlist_lyrics <- gsub("Rainw", "Rain", unlist_lyrics)
unlist_lyrics <- gsub("daying", "day", unlist_lyrics)
unlist_lyrics <- gsub("everythingg", "everything", unlist_lyrics)
unlist_lyrics <- gsub("flyash", "fly", unlist_lyrics)
unlist_lyrics <- gsub("gdness", "goodness", unlist_lyrics)
unlist_lyrics <- gsub("heartt", "heart", unlist_lyrics)
unlist_lyrics <- gsub("highlightt", "highlight", unlist_lyrics)
unlist_lyrics <- gsub("imaginee", "imagine", unlist_lyrics)
unlist_lyrics <- gsub("itin", "waiting", unlist_lyrics)
unlist_lyrics <- gsub("Puzzlee", "Puzzle", unlist_lyrics)
unlist_lyrics <- gsub("slowlyy", "slowly", unlist_lyrics)
unlist_lyrics <- gsub("styleish", "stylish", unlist_lyrics)
unlist_lyrics <- gsub("빠져들어겠지", "빠져들어", unlist_lyrics)
unlist_lyrics <- gsub("ton", "tone", unlist_lyrics)
unlist_lyrics <- gsub("whe", "where", unlist_lyrics)
unlist_lyrics <- gsub("kisss", "kiss", unlist_lyrics)
unlist_lyrics <- gsub("lightts", "light", unlist_lyrics)
unlist_lyrics <- gsub("Alrightt", "Alright", unlist_lyrics)
unlist_lyrics <- gsub("anythin", "anything", unlist_lyrics)
unlist_lyrics <- gsub("Everydayy", "Everyday", unlist_lyrics)
unlist_lyrics <- gsub("Psychoticc", "Psychotic", unlist_lyrics)
unlist_lyrics <- gsub("stopry", "story", unlist_lyrics)
unlist_lyrics <- gsub("sundayy", "sunday", unlist_lyrics)
unlist_lyrics <- gsub("용기나질", "용기", unlist_lyrics)
unlist_lyrics <- gsub("울려오잖", "울려", unlist_lyrics)
unlist_lyrics <- gsub("약속했잖", "약속", unlist_lyrics)
unlist_lyrics <- gsub("자유롭", "자유", unlist_lyrics)
unlist_lyrics <- gsub("Befor", "before", unlist_lyrics)
unlist_lyrics <- gsub("Anywhe", "Anywhere", unlist_lyrics)
unlist_lyrics <- gsub("blahh", "blah", unlist_lyrics)
unlist_lyrics <- gsub("dayncing", "dancing", unlist_lyrics)
unlist_lyrics <- gsub("destinyy", "destiny", unlist_lyrics)
unlist_lyrics <- gsub("everydayy", "everyday", unlist_lyrics)
unlist_lyrics <- gsub("Hea", "Head", unlist_lyrics)
unlist_lyrics <- gsub("Hurrican", "Hurricane", unlist_lyrics)
unlist_lyrics <- gsub("lightt", "light", unlist_lyrics)
unlist_lyrics <- gsub("Lonel", "Lonely", unlist_lyrics)
unlist_lyrics <- gsub("runy", "run", unlist_lyrics)
unlist_lyrics <- gsub("somedayy", "someday", unlist_lyrics)
unlist_lyrics <- gsub("Spotlightt", "Spotlight", unlist_lyrics)
unlist_lyrics <- gsub("Sundayy", "sunday", unlist_lyrics)
unlist_lyrics <- gsub("Todayy", "today", unlist_lyrics)
unlist_lyrics <- gsub("whatt", "what", unlist_lyrics)
unlist_lyrics <- gsub("YeYesterdayday", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("레파토", "레파토리", unlist_lyrics)
unlist_lyrics <- gsub("bluee", "blue", unlist_lyrics)
unlist_lyrics <- gsub("brighttnes", "brightness", unlist_lyrics)
unlist_lyrics <- gsub("Bubblee", "Bubble", unlist_lyrics)
unlist_lyrics <- gsub("Can't", "can't", unlist_lyrics)
unlist_lyrics <- gsub("Colo", "color", unlist_lyrics)
unlist_lyrics <- gsub("Errdayy", "Errday", unlist_lyrics)
unlist_lyrics <- gsub("Eyy", "Ey", unlist_lyrics)
unlist_lyrics <- gsub("Contro", "Control", unlist_lyrics)
unlist_lyrics <- gsub("Hamony", "Harmony", unlist_lyrics)
unlist_lyrics <- gsub("Kiing", "Killing", unlist_lyrics)
unlist_lyrics <- gsub("Kisssing", "Kissing", unlist_lyrics)
unlist_lyrics <- gsub("Memoryy", "Memory", unlist_lyrics)
unlist_lyrics <- gsub("MiYesterday", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("MyYesterday", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("morningg", "morning", unlist_lyrics)
unlist_lyrics <- gsub("oncee", "once", unlist_lyrics)
unlist_lyrics <- gsub("Shakee", "Shake", unlist_lyrics)
unlist_lyrics <- gsub("SEE", "see", unlist_lyrics)
unlist_lyrics <- gsub("Sho", "Show", unlist_lyrics)
unlist_lyrics <- gsub("somewhe", "somewhere", unlist_lyrics)
unlist_lyrics <- gsub("sunlightt", "sunlight", unlist_lyrics)
unlist_lyrics <- gsub("Welcomee", "Welcome", unlist_lyrics)
unlist_lyrics <- gsub("Whatt's", "What's", unlist_lyrics)
unlist_lyrics <- gsub("Wingsd", "Wings", unlist_lyrics)
unlist_lyrics <- gsub("heartre", "heart", unlist_lyrics)
unlist_lyrics <- gsub("Wherere", "Where", unlist_lyrics)
unlist_lyrics <- gsub("babyb", "baby", unlist_lyrics)
unlist_lyrics <- gsub("highh", "high", unlist_lyrics)
unlist_lyrics <- gsub("Sundayay", "Sunday", unlist_lyrics)
unlist_lyrics <- gsub("girlllrl", "girl", unlist_lyrics)
unlist_lyrics <- gsub("Cherryrry", "Cherry", unlist_lyrics)
unlist_lyrics <- gsub("caree", "care", unlist_lyrics)
unlist_lyrics <- gsub("areound", "around", unlist_lyrics)
unlist_lyrics <- gsub("crazyy", "crazy", unlist_lyrics)
unlist_lyrics <- gsub("LiYesterdayn", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("^mov$", "move", unlist_lyrics)
unlist_lyrics <- gsub("^min$", "mine", unlist_lyrics)
unlist_lyrics <- gsub("^mov$", "move", unlist_lyrics)
unlist_lyrics <- gsub("^Yesterday", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("Yesterday$", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("^Yesterday$", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("dayrling", "darling", unlist_lyrics)
unlist_lyrics <- gsub("heartt", "heart", unlist_lyrics)
unlist_lyrics <- gsub("^Paret$", "Party", unlist_lyrics)
unlist_lyrics <- gsub("^Wingss$", "Wings", unlist_lyrics)
unlist_lyrics <- gsub("^baby", "baby", unlist_lyrics)
unlist_lyrics <- gsub("baby$", "baby", unlist_lyrics)
unlist_lyrics <- gsub("Anywhererere", "Anywhere", unlist_lyrics)
unlist_lyrics <- gsub("Cherryck", "Cherry", unlist_lyrics)
unlist_lyrics <- gsub("Cherrymistry", "Chemistry", unlist_lyrics)
unlist_lyrics <- gsub("DreI'ms", "Dreams", unlist_lyrics)
unlist_lyrics <- gsub("flyow", "flow", unlist_lyrics)
unlist_lyrics <- gsub("^girlls$", "girl", unlist_lyrics)
unlist_lyrics <- gsub("Lonelyy", "Lonely", unlist_lyrics)
unlist_lyrics <- gsub("Pareadis", "Paradise", unlist_lyrics)
unlist_lyrics <- gsub("Showw", "Show", unlist_lyrics)
unlist_lyrics <- gsub("sI'me", "I'm", unlist_lyrics)
unlist_lyrics <- gsub("Starery", "Starry", unlist_lyrics)
unlist_lyrics <- gsub("Sundaya", "Sunday", unlist_lyrics)
unlist_lyrics <- gsub("Whatt", "What", unlist_lyrics)
unlist_lyrics <- gsub("Woworldd", "world", unlist_lyrics)
unlist_lyrics <- gsub("^youre$", "you're", unlist_lyrics)
unlist_lyrics <- gsub("areoun", "around", unlist_lyrics)
unlist_lyrics <- gsub("^babyd$", "baby", unlist_lyrics)
unlist_lyrics <- gsub("^bloomingg$", "Blooming", unlist_lyrics)
unlist_lyrics <- gsub("^blooming$", "Blooming", unlist_lyrics)
unlist_lyrics <- gsub("beforere", "before", unlist_lyrics)
unlist_lyrics <- gsub("brightnes", "brightness", unlist_lyrics)
unlist_lyrics <- gsub("dreI'm", "I'm", unlist_lyrics)
unlist_lyrics <- gsub("^girl", "girl", unlist_lyrics)
unlist_lyrics <- gsub("moodnlyigh", "moonlight", unlist_lyrics)
unlist_lyrics <- gsub("^shin$", "shine", unlist_lyrics)
unlist_lyrics <- gsub("Starelight", "starlight", unlist_lyrics)
unlist_lyrics <- gsub("^Stor$", "story", unlist_lyrics)
unlist_lyrics <- gsub("^storym$", "story", unlist_lyrics)
unlist_lyrics <- gsub("^tak$", "take", unlist_lyrics)
unlist_lyrics <- gsub("toneight", "tonight", unlist_lyrics)
unlist_lyrics <- gsub("vacatio", "vacation", unlist_lyrics)
unlist_lyrics <- gsub("wawaiting", "waiting", unlist_lyrics)
unlist_lyrics <- gsub("Whatt's", "What's", unlist_lyrics)
unlist_lyrics <- gsub("빠져들어어갔", "빠져들어", unlist_lyrics)
unlist_lyrics <- gsub("Yesterdayp", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("^babyy$", "baby", unlist_lyrics)
unlist_lyrics <- gsub("^babyck$", "baby", unlist_lyrics)
unlist_lyrics <- gsub("^DreI'm$", "I'm", unlist_lyrics)
unlist_lyrics <- gsub("^goo$", "Good", unlist_lyrics)
unlist_lyrics <- gsub("^outt$", "out", unlist_lyrics)
unlist_lyrics <- gsub("^Yesterdayr$", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("^YeYesterdayrday$", "Yesterday", unlist_lyrics)
unlist_lyrics <- gsub("^Calll$", "Call", unlist_lyrics)
unlist_lyrics <- gsub("^girlllve$", "girl", unlist_lyrics)
unlist_lyrics <- gsub("^Haremony$", "Harmony", unlist_lyrics)
unlist_lyrics <- gsub("^shoutld$", "should", unlist_lyrics)
unlist_lyrics <- gsub("^somewhererere$", "somewhere", unlist_lyrics)
unlist_lyrics <- gsub("^ski$", "skip", unlist_lyrics)
unlist_lyrics <- gsub("^Vacatio$", "vacation", unlist_lyrics)
unlist_lyrics <- gsub("^Wonderlan$", "wonderland", unlist_lyrics)
unlist_lyrics <- gsub("^Worl$", "world", unlist_lyrics)
unlist_lyrics <- gsub("^waitingg$", "waiting", unlist_lyrics)
unlist_lyrics <- gsub("^twic$", "twice", unlist_lyrics)
unlist_lyrics <- gsub("^목소리리$", "목소리", unlist_lyrics)
# 뜻 없는 단어 삭제, 해당 단어만 지우기 위해 첫 문자 ^와 마지막 문자 $ 표시
unlist_lyrics <- gsub("^Wo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Yo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Ba$", "", unlist_lyrics)
unlist_lyrics <- gsub("^bo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Sa$", "", unlist_lyrics)
unlist_lyrics <- gsub("^moo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ll$", "", unlist_lyrics)
unlist_lyrics <- gsub("^re$", "", unlist_lyrics)
unlist_lyrics <- gsub("^tal$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ou$", "", unlist_lyrics)
unlist_lyrics <- gsub("^wa$", "", unlist_lyrics)
unlist_lyrics <- gsub("^oo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ooo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^sho$", "", unlist_lyrics)
unlist_lyrics <- gsub("^fromze$", "", unlist_lyrics)
unlist_lyrics <- gsub("^fromzen$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Ho$", "", unlist_lyrics)
unlist_lyrics <- gsub("^stayrte$", "", unlist_lyrics)
unlist_lyrics <- gsub("^staytio$", "", unlist_lyrics)
unlist_lyrics <- gsub("^nderlan$", "", unlist_lyrics)
unlist_lyrics <- gsub("^rl$", "", unlist_lyrics)
unlist_lyrics <- gsub("^rry$", "", unlist_lyrics)
unlist_lyrics <- gsub("^stayrs$", "", unlist_lyrics)
unlist_lyrics <- gsub("^sur$", "", unlist_lyrics)
unlist_lyrics <- gsub("^thatn$", "", unlist_lyrics)
unlist_lyrics <- gsub("^cl$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ay$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ye$", "", unlist_lyrics)
unlist_lyrics <- gsub("^cae$", "", unlist_lyrics)
unlist_lyrics <- gsub("^te$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Oo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^yr$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ut$", "", unlist_lyrics)
unlist_lyrics <- gsub("^nna$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Curis$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ld$", "", unlist_lyrics)
unlist_lyrics <- gsub("^fu$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Fw$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Pat$", "", unlist_lyrics)
unlist_lyrics <- gsub("^sect$", "", unlist_lyrics)
unlist_lyrics <- gsub("^va$", "", unlist_lyrics)
unlist_lyrics <- gsub("^fu$", "", unlist_lyrics)
unlist_lyrics <- gsub("^al$", "", unlist_lyrics)
unlist_lyrics <- gsub("^alys$", "", unlist_lyrics)
unlist_lyrics <- gsub("^mo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^nt$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ose$", "", unlist_lyrics)
unlist_lyrics <- gsub("^teite$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ae$", "", unlist_lyrics)
unlist_lyrics <- gsub("^해진$", "", unlist_lyrics)
unlist_lyrics <- gsub("^이기$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Alys$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Blming$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Ca$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ch$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Gd$", "", unlist_lyrics)
unlist_lyrics <- gsub("^gis$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Hea$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ndezvs$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Paadis$", "", unlist_lyrics)
unlist_lyrics <- gsub("^로운$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Anyplayc$", "", unlist_lyrics)
unlist_lyrics <- gsub("^blming$", "", unlist_lyrics)
unlist_lyrics <- gsub("^blmingg$", "", unlist_lyrics)
unlist_lyrics <- gsub("^dnlyigh$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Cal$", "", unlist_lyrics)
unlist_lyrics <- gsub("^don$", "", unlist_lyrics)
unlist_lyrics <- gsub("^fa$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Fa$", "", unlist_lyrics)
unlist_lyrics <- gsub("^iting$", "", unlist_lyrics)
unlist_lyrics <- gsub("^gi$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Sma$", "", unlist_lyrics)
unlist_lyrics <- gsub("^sht$", "", unlist_lyrics)
unlist_lyrics <- gsub("^shtld$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Sl$", "", unlist_lyrics)
unlist_lyrics <- gsub("^mirae$", "", unlist_lyrics)
unlist_lyrics <- gsub("^slo$", "", unlist_lyrics)
unlist_lyrics <- gsub("^snd$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Shh$", "", unlist_lyrics)
unlist_lyrics <- gsub("^staightt$", "", unlist_lyrics)
unlist_lyrics <- gsub("^sti$", "", unlist_lyrics)
unlist_lyrics <- gsub("^stoprym$", "", unlist_lyrics)
unlist_lyrics <- gsub("^styleis$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Shh$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Va$", "", unlist_lyrics)
unlist_lyrics <- gsub("^ww$", "", unlist_lyrics)
unlist_lyrics <- gsub("^y'$", "", unlist_lyrics)
unlist_lyrics <- gsub("^zm$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Zm$", "", unlist_lyrics)
unlist_lyrics <- gsub("^노초$", "", unlist_lyrics)
unlist_lyrics <- gsub("^'t$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Headre$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Headred$", "", unlist_lyrics)
unlist_lyrics <- gsub("^Headret$", "", unlist_lyrics)
## ------(바꾸기 end) -------------------------------------------------- ####

# 찾아바꾸기 gsub() 함수를 실행한 후 형태소 테이블 확인
lyrics_table <- table(unlist_lyrics)
lyrics_table
sort(lyrics_table, decreasing = T)

# 두 글자 이상 형태소만 남기도록 필터링
unlist_lyrics2 <- Filter(function(x) { nchar(x) >= 2 }, unlist_lyrics)
unlist_lyrics2
str(unlist_lyrics2)
is.vector(unlist_lyrics2)

# 필터링한 형태소 벡터를 테이블로 변환 : 형태소의 사용빈도 재확인
lyrics_table2 <- table(unlist_lyrics2)
lyrics_table2
sort(lyrics_table2, decreasing = T)  # 내림차순 정렬

# 워드클라우드 실행
wordcloud2(lyrics_table2)

wordcloud2(lyrics_table2, color = "random-light", 
           backgroundColor = "black")

wordcloud2(lyrics_table2, size = 2, shape = "pentagon", 
           color = "random-light", backgroundColor = "Black")
?wordcloud2

wordcloud2(lyrics_table2, 
           rotateRatio = 1,
           minRotation = -pi/6, 
           maxRotation = -pi/6,
           backgroundColor = "white") 

# shape = 'cardioid': apple or heart shape curve, the most known polar equation
wordcloud2(lyrics_table2, size = 1.7, shape = "cardioid", 
           minRotation = -pi/8, maxRotation = pi/8,
           color = "random-dark", backgroundColor = rgb(0.05, 0.9, 0.4),
           fontFamily = "맑은 고딕", fontWeight = "bold") 

# shape = 'triangle-forward'
wordcloud2(lyrics_table2, size = 1.5, shape = "triangle-forward", 
           rotateRatio = 1, minRotation = 0, maxRotation = 0,
           color = "random-light", backgroundColor = '#2024AB') 
